### ISSUE TITLE
[Feature Request] - Having majority percentile in additon to min/max/avg

### ISSUE THREAD

**Issue by DesertIce** [exeldro/obs-source-profiler#1]
Many profiling applications show high percentile values as part of their statistical output. Commonly 95th and 99th percentiles to filter out "spikey" outliers and get a more representative value. Attached is a graphical example from a gaming benchmark.
![Crysis-3-CPU-benchmark-frame-time](https://github.com/user-attachments/assets/e9ca9b28-b687-47cf-ae2a-ebd802c4cda1)

**Comment by exeldro** [comment]
The plugin depends on the data provided by the obs core. The percentiles are not part of that data. To get that in the data it would require changes to OBS.

**Comment by DesertIce** [comment]
Ah fair enough. I was thinking if the raw data was more available on the plug-in side.
