### ISSUE TITLE
[Feature Request] In "Scene Nested" view, only show the current scene tree.

### ISSUE THREAD

**Issue by FiniteSingularity** [exeldro/obs-source-profiler#8]
Currently, the "Scene Nested" view shows both the current scene (with an expandable tree), as well as all scenes that are used at the same level of the current scene.  This is a bit confusing, as it shows those nested scenes both inside the current scene tree, as well as at the top-most level.

I think it would make the UI more clear to *only* show the current scene + its tree, rather than duplicating internal scenes (see attached screenshot).  The exception to this in my example, is the once scene component (`[Scene Component] Bars Overlay`) which is  used by Downstream Keyer.

![image](https://github.com/user-attachments/assets/4291d075-c281-4efb-8464-6489c9763171)

**Comment by exeldro** [comment]
This should be fixed in version 0.0.6

**Comment by FiniteSingularity** [comment]
thanks Exeldro!  Looks like it is fixed in 0.0.6.  Closing.
